source 'https://rubygems.org'

gem 'rake'
gem 'afmotion'
gem 'bubble-wrap'
gem 'motion-cocoapods'
gem 'sugarcube', require: [
  'sugarcube-uikit',
  'sugarcube-attributedstring'
]

gem "webstub" # used for stub web
